#!/usr/bin/env bash
#  Install nginx web server

sudo pt-get update
sudo ufw disable
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

echo "server {
 listen 80;
 root var/www/html;
 index index.html;
}" > /etc/nginx/sites-available/default

service nginx restart
