#!/usr/bin/env bash
#  Install nginx web server

sudo pt-get update
ufw disable
sudo apt-get install -y nginx

echo "server {
 listen 80;
 location / {
  echo 'Hello World!';
  }
}" > /etc/nginx/sites-available/default

service nginx restart
