#!/usr/bin/env bash
# checking which server is performing the task

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/# server_tokens off;/server_tokens off;\n	add_header X-Served-By $hostname;/g' /etc/nginx/nginx.conf

sudo systemctl restart nginx
