#!/usr/bin/env bash
# Backing up all databases into a file called backup.sql
# zipping the backup file into a file ending in .ta.gz

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
