#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.
# check if ip address is provided
# checks the IP address
if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
	ping -c 5 "$1"
else
	echo "Usage: $0 {IP_ADDRESS}"
fi
