#!/usr/bin/env bash

# installing ufw

sudo apt install ufw
sudo ufw fefault deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status
