#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

#first check if script is running as root
if [[ $EUID -ne 0 ]];
then
	echo "This script must be run as root"
	exit 1
fi

# Define the desired IP addresses
localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

# Update the etc/hosts file
sed -i "/localhost/ s/127.0.0.1/$localhost_ip/" /etc/hosts

# Add an entry for facebook
echo "$facebook_ip facebook.com" >> /etc/hosts
