#!/usr/bin/env bash
# a Bash script that listens on port 98 on localhost.

# check is its runnig as root
if [[ $EUID -ne 0 ]];
then
	echo "This script must be run as root"
fi

# Listen on port 98
nc -l localhost 98
